# Generated by Django 5.0.6 on 2025-09-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='responses.coursesession'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='responses.coursesession'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='question_context',
            field=models.ForeignKey(blank=True, help_text='Question this turn relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responses.questionresponse'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['user', 'course', 'status'], name='responses_c_user_id_9449ac_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['status', 'last_activity_at'], name='responses_c_status_107f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['user', 'status'], name='responses_c_user_id_2deb68_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['session', 'status'], name='responses_q_session_fb9d67_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['question_id', 'status'], name='responses_q_questio_f55fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['session', 'question_number'], name='responses_q_session_f33f62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('session', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'turn_number'], name='responses_c_session_34eb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'role'], name='responses_c_session_af068c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationturn',
            unique_together={('session', 'turn_number')},
        ),
    ]
