[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "never"

[experimental]
# Enable WebSocket support
websockets = true

# Railway WebSocket configuration
[deployment]
webSocketUpgradeMode = "auto"
asgiEnabled = true
websocketTimeout = 300