# Generated by Django 5.0.6 on 2025-11-02 06:34

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('anonymous_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_photo_path)),
                ('account_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('_encrypted_pii', models.TextField(blank=True, help_text='Encrypted sensitive personal data', null=True)),
                ('default_organization', models.ForeignKey(blank=True, help_text='Default organization when user accesses admin features', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_admin_users', to='organizations.organization')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key to retrieve guest attempts', max_length=40, null=True)),
                ('guest_attempt_ids', models.JSONField(default=dict, help_text='Maps step_id to attempt_id from onboarding flow')),
                ('flow_id', models.CharField(default='user-onboarding-v1', help_text='Which onboarding flow they completed', max_length=100)),
                ('subscribed_to_updates', models.BooleanField(default=True, help_text='Opted in to receive product updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When the guest lead registered as a full user', null=True)),
                ('converted_to_user', models.ForeignKey(blank=True, help_text='User account created with this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_guest_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_guest_email_2d4d90_idx'), models.Index(fields=['created_at'], name='users_guest_created_a89507_idx'), models.Index(fields=['converted_to_user'], name='users_guest_convert_15c470_idx')],
            },
        ),
    ]
