# Generated by Django 5.0.6 on 2025-09-09 19:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_encrypted_pii',
            field=models.TextField(blank=True, help_text='Encrypted sensitive personal data', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_photo_path),
        ),
    ]
