# Generated by Django 5.0.6 on 2025-09-16 17:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.UUIDField(blank=True, help_text='Original template ID for tracking updates', null=True)),
                ('editable', models.BooleanField(default=True, help_text='Can only be set by original creator')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('is_shared', models.BooleanField(default=False, help_text='Can be enrolled in by other users')),
                ('is_active', models.BooleanField(default=True, help_text='Available for new enrollments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('finish_date', models.DateField(help_text='Target completion date')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Display order within quest')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='quests.milestone')),
            ],
            options={
                'ordering': ['quest', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Display order within quest')),
                ('estimated_finish_days', models.PositiveIntegerField(help_text='Days from enrollment to complete')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='quests.milestonetemplate')),
            ],
            options={
                'ordering': ['quest_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateField(help_text='Target completion date (calculated from enrollment + estimated days)')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes for this milestone")),
                ('milestone_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quests.milestonetemplate')),
            ],
            options={
                'ordering': ['enrollment', 'milestone_template__order'],
            },
        ),
    ]
