# Generated by Django 5.0.6 on 2025-09-09 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.UUIDField(blank=True, help_text='Original template ID for tracking updates', null=True)),
                ('editable', models.BooleanField(default=True, help_text='Can only be set by original creator')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('finish_date', models.DateField(help_text='Target completion date')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Display order within quest')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='quests.milestone')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='quests.quest')),
            ],
            options={
                'ordering': ['quest', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['user', 'created_at'], name='quests_ques_user_id_bef9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['created_by'], name='quests_ques_created_36958d_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['template_id'], name='quests_ques_templat_1c2f77_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['quest', 'order'], name='quests_mile_quest_i_2114d3_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['status'], name='quests_mile_status_08cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['finish_date'], name='quests_mile_finish__1edebc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('quest', 'order')},
        ),
    ]
