# Generated by Django 5.0.6 on 2025-09-17 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='quests.quest'),
        ),
        migrations.AddField(
            model_name='questenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestoneprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to='quests.questenrollment'),
        ),
        migrations.AddField(
            model_name='questtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quest_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questenrollment',
            name='quest_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quests.questtemplate'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='quest_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='quests.questtemplate'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['user', 'created_at'], name='quests_ques_user_id_bef9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['created_by'], name='quests_ques_created_36958d_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['template_id'], name='quests_ques_templat_1c2f77_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['quest', 'order'], name='quests_mile_quest_i_2114d3_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['status'], name='quests_mile_status_08cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['finish_date'], name='quests_mile_finish__1edebc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('quest', 'order')},
        ),
        migrations.AddIndex(
            model_name='milestoneprogress',
            index=models.Index(fields=['enrollment', 'status'], name='quests_mile_enrollm_c425b5_idx'),
        ),
        migrations.AddIndex(
            model_name='milestoneprogress',
            index=models.Index(fields=['status'], name='quests_mile_status_fc6869_idx'),
        ),
        migrations.AddIndex(
            model_name='milestoneprogress',
            index=models.Index(fields=['finish_date'], name='quests_mile_finish__7062b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestoneprogress',
            unique_together={('enrollment', 'milestone_template')},
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['created_by'], name='quests_ques_created_fcfa93_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['is_shared', 'is_active'], name='quests_ques_is_shar_79c3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['category'], name='quests_ques_categor_9132d5_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['user', 'status'], name='quests_ques_user_id_d36963_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['quest_template', 'status'], name='quests_ques_quest_t_a62a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['enrolled_at'], name='quests_ques_enrolle_1e444d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questenrollment',
            unique_together={('user', 'quest_template')},
        ),
        migrations.AddIndex(
            model_name='milestonetemplate',
            index=models.Index(fields=['quest_template', 'order'], name='quests_mile_quest_t_8d07cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonetemplate',
            unique_together={('quest_template', 'order')},
        ),
    ]
