# Generated by Django 5.0.6 on 2025-11-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityversion',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quests.activity'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='activity_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.activityversion'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='activity_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.activityversion'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='activity_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.activityversion'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='activity_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='quests.activityversion'),
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='quests.page'),
        ),
        migrations.AddField(
            model_name='pageprogress',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_progress', to='quests.attempt'),
        ),
        migrations.AddField(
            model_name='pageprogress',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.page'),
        ),
        migrations.AddField(
            model_name='questenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='quest_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.questdefinition'),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quest_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.questinstance'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='quest_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.questinstance'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='quest_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.questinstance'),
        ),
        migrations.AddField(
            model_name='questitemdefinition',
            name='activity',
            field=models.ForeignKey(blank=True, help_text="Reference to Activity if item_type is 'activity'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_definitions', to='quests.activity'),
        ),
        migrations.AddField(
            model_name='questitemdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_item_definitions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='questitemprogress',
            name='activity_submission',
            field=models.ForeignKey(blank=True, help_text='Link to completed activity submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_progress', to='quests.activitysubmission'),
        ),
        migrations.AddField(
            model_name='questitemprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progress', to='quests.questenrollment'),
        ),
        migrations.AddField(
            model_name='questtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this quest', on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questtemplate',
            name='organization',
            field=models.ForeignKey(help_text='Organization this quest belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quest_templates', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='questenrollment',
            name='quest_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quests.questtemplate'),
        ),
        migrations.AddField(
            model_name='questtemplateitem',
            name='item_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_usages', to='quests.questitemdefinition'),
        ),
        migrations.AddField(
            model_name='questtemplateitem',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Items that must be completed before this one', related_name='dependent_items', to='quests.questtemplateitem'),
        ),
        migrations.AddField(
            model_name='questtemplateitem',
            name='quest_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='quests.questtemplate'),
        ),
        migrations.AddField(
            model_name='questitemprogress',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quests.questtemplateitem'),
        ),
        migrations.AddField(
            model_name='response',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quests.attempt'),
        ),
        migrations.AddField(
            model_name='response',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.page'),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quests.page'),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quests.activitysubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='activityversion',
            unique_together={('activity', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('activity_version', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('page', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='pageprogress',
            unique_together={('attempt', 'page')},
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'started_at'], name='quests_atte_user_id_f7d8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status'], name='quests_atte_user_id_bed185_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['activity_version', 'user', 'started_at'], name='quests_atte_activit_689869_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status', 'started_at'], name='quests_atte_user_id_9c0a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysubmission',
            index=models.Index(fields=['user', 'completed_at'], name='quests_acti_user_id_fc4b11_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysubmission',
            index=models.Index(fields=['activity_version', 'user', 'completed_at'], name='quests_acti_activit_339155_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysubmission',
            index=models.Index(fields=['user', 'activity_version', 'completed_at'], name='quests_acti_user_id_246875_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['user', 'activity_version'], name='quests_acti_user_id_8e4fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['expires_at'], name='quests_acti_expires_979d85_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['user', 'last_activity'], name='quests_acti_user_id_d45e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitysession',
            unique_together={('user', 'activity_version')},
        ),
        migrations.AddIndex(
            model_name='questitemdefinition',
            index=models.Index(fields=['item_type'], name='quests_ques_item_ty_46e557_idx'),
        ),
        migrations.AddIndex(
            model_name='questitemdefinition',
            index=models.Index(fields=['organization'], name='quests_ques_organiz_ca3e16_idx'),
        ),
        migrations.AddIndex(
            model_name='questitemdefinition',
            index=models.Index(fields=['item_type', 'organization'], name='quests_ques_item_ty_11701a_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['organization', 'status'], name='quests_ques_organiz_542621_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['is_public', 'status'], name='quests_ques_is_publ_771e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['created_by'], name='quests_ques_created_fcfa93_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['user', 'status'], name='quests_ques_user_id_d36963_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['quest_template', 'status'], name='quests_ques_quest_t_a62a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['enrolled_at'], name='quests_ques_enrolle_1e444d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questenrollment',
            unique_together={('user', 'quest_template')},
        ),
        migrations.AddIndex(
            model_name='questtemplateitem',
            index=models.Index(fields=['quest_template', 'order'], name='quests_ques_quest_t_540b96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questtemplateitem',
            unique_together={('quest_template', 'item_definition'), ('quest_template', 'order')},
        ),
        migrations.AddIndex(
            model_name='questitemprogress',
            index=models.Index(fields=['enrollment', 'status'], name='quests_ques_enrollm_2a463f_idx'),
        ),
        migrations.AddIndex(
            model_name='questitemprogress',
            index=models.Index(fields=['template_item', 'status'], name='quests_ques_templat_1587b5_idx'),
        ),
        migrations.AddIndex(
            model_name='questitemprogress',
            index=models.Index(fields=['target_date'], name='quests_ques_target__bb0b85_idx'),
        ),
        migrations.AddIndex(
            model_name='questitemprogress',
            index=models.Index(fields=['status', 'target_date'], name='quests_ques_status_43eec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questitemprogress',
            unique_together={('enrollment', 'template_item')},
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['attempt', 'created_at'], name='quests_resp_attempt_c681f9_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['attempt', 'question_id'], name='quests_resp_attempt_c25fae_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresponse',
            index=models.Index(fields=['submission', 'created_at'], name='quests_subm_submiss_8a75ba_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresponse',
            index=models.Index(fields=['submission', 'question_id'], name='quests_subm_submiss_0ddb51_idx'),
        ),
    ]
