# Generated by Django 5.0.6 on 2025-09-16 05:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('is_shared', models.BooleanField(default=False, help_text='Can be enrolled in by other users')),
                ('is_active', models.BooleanField(default=True, help_text='Available for new enrollments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quest_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_enrollments', to=settings.AUTH_USER_MODEL)),
                ('quest_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quests.questtemplate')),
            ],
            options={
                'ordering': ['enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Display order within quest')),
                ('estimated_finish_days', models.PositiveIntegerField(help_text='Days from enrollment to complete')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='quests.milestonetemplate')),
                ('quest_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='quests.questtemplate')),
            ],
            options={
                'ordering': ['quest_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateField(help_text='Target completion date (calculated from enrollment + estimated days)')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes for this milestone")),
                ('milestone_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quests.milestonetemplate')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to='quests.questenrollment')),
            ],
            options={
                'ordering': ['enrollment', 'milestone_template__order'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='quests_mile_enrollm_c425b5_idx'), models.Index(fields=['status'], name='quests_mile_status_fc6869_idx'), models.Index(fields=['finish_date'], name='quests_mile_finish__7062b2_idx')],
                'unique_together': {('enrollment', 'milestone_template')},
            },
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['created_by'], name='quests_ques_created_fcfa93_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['is_shared', 'is_active'], name='quests_ques_is_shar_79c3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['category'], name='quests_ques_categor_9132d5_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['user', 'status'], name='quests_ques_user_id_d36963_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['quest_template', 'status'], name='quests_ques_quest_t_a62a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='questenrollment',
            index=models.Index(fields=['enrolled_at'], name='quests_ques_enrolle_1e444d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questenrollment',
            unique_together={('user', 'quest_template')},
        ),
        migrations.AddIndex(
            model_name='milestonetemplate',
            index=models.Index(fields=['quest_template', 'order'], name='quests_mile_quest_t_8d07cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonetemplate',
            unique_together={('quest_template', 'order')},
        ),
    ]
